### ISSUE TITLE
Vídeos support? 

### ISSUE THREAD

**Issue by RaulKite** [mbzuai-oryx/LLaVA-pp#3]
Is there any way to use a video as input?

thanks

**Comment by mmaaz60** [comment]
Hi @RaulKite

I appreciate your interest in our work. The Phi-3-V and LLaMA-3-V models can be used with video inputs. However, the responses might not be good as the models are fine-tuned with image data only. 

You can use a [spatio-temporal feature extraction](https://github.com/mbzuai-oryx/Video-ChatGPT/blob/f27bf8c29b77efcc2ca07e398e92aa1de09f5063/video_chatgpt/inference.py#L90) method from [Video-ChatGPT](https://github.com/mbzuai-oryx/Video-ChatGPT.git) to extract video-features and input them to the LLM (instead of image features) for generating response.

A more appropriate approach would be to fine-tune Phi-3-V and LLaMA-3-V models on [VideoInstruct100K](https://huggingface.co/datasets/MBZUAI/VideoInstruct-100K) dataset to have a more comprehensive video understanding.

I hope it will help. Please let us know if you have any questions. Thank You
